# Generated by Django 3.2.6 on 2023-02-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.department')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel.hostel')),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
